Google sheets
NikitaShlapak/OSO_bot pull request #4
Opened 2024-07-08 13:32 UTC by NikitaChichikin

2024-07-08 13:35 UTC, NikitaShlapak commented on utils/test1.py
> +SCOPES = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
Такие вещи лучше выносить в отдельный файл с настройками

2024-07-08 13:36 UTC, NikitaShlapak commented on utils/test1.py
> +SAMPLE_RANGE_NAME = "Кружок Программирования!A2:B50"
Это не константы. Их не нужно большими буквам называть. ID в целом можно, но тогда см предыдущий коммент

2024-07-08 13:38 UTC, NikitaShlapak commented on utils/test1.py
> +    print(err)
работа с ошибками это, конечно, хорошо, но если обрабатывать, то лучше уж обрабатывать по полной. Ну или если просто писать об ошибке, то как минимум в .log-файл

2024-07-08 13:39 UTC, NikitaShlapak commented on utils/test1.py
> +    otvet=[]
Бан за такие названия переменных. Никаких транслитераций.

2024-07-08 13:42 UTC, NikitaShlapak commented on utils/test1.py
> +  main()
Ну вызвал ты эту функцию, ну сделала она внутри себя два листа с ответами. А дальше что? Во-первых, эту информацию надо возвращать, чтобы её дальше обрабатывали. Во-вторых, мы договаривались, что она будет в виде словаря, в котором по ключу вопрос, по значению - ответ

2024-07-08 13:43 UTC, NikitaShlapak requested changes
Есть несколько вещей, которые надо поправить

2024-07-15 08:47 UTC, NikitaShlapak commented on utils/test1.py
Что это за файл? Зачем он нужен? Если без него проект будет работать, то удалить

2024-07-15 08:47 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +scopes = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
Это всё ещё нужно вынести в env.py

2024-07-15 08:49 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +print(dictionary_of_council_of_dormitories)
В финальной версии кода принтов быть не должно

2024-07-15 08:52 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +    return dictionary
Я вызываю эту функцию. Мне возвращается словарь. Откуда мне знать, к чему этот словарь относится? Функция должна на вход принимать какой-то аргумент, который определяет, информацию о каком объединении она должна вернуть.

2024-07-15 08:56 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +    return
Это всё ещё неправильная обработка исключений. При возникновении HttpError нужно повторять попытку подключения. Или на худой конец возвращать сообщение об ошибке. Кроме того, except стоит всё ещё слишком поздно. В 39 строчке и далее HttpError точно не возникнет.

2024-07-15 09:02 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +    if not values:
Плохо. Логические операторы к спискам применять нельзя. Нужно использовать либо any(), либо all(), либо (что в данном случае будет лучшим решением) возвращать не пустой список а None и проверять на is None

2024-07-15 09:04 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +      return
Плохо. Я вызвал функцию, она закончилась на этой строчке. Мне пришёл None. Откуда мне знать, что это значит? Нужно либо возвращать сообщение о соответствующей ошибке, либо бросать исключение и обрабатывать уже его

2024-07-15 09:05 UTC, NikitaShlapak requested changes
Исправлены не все комментарии

2024-07-16 14:10 UTC, NikitaChichikin commented
Были исправлены предыдущие ошибки но остались вопросы по поводу ошибки Httpserror

2024-07-18 11:10 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +dictionary_of_council_of_dormitories=reading_google_sheets(sample_range_name_of_council_of_dormitories)
Опять не то. Эти переменные не нужны. Тем более в глобальной области видимости. Я хочу импортировать твою функцию, вызывать её, передавая аргументом странпицу таблицы и получать нужный мне словарь. Один. Ничего лишнего мне не нужно

2024-07-18 11:11 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +    return dictionary
всё хорошо, только непонятно что за i и на кой она тут нужна

2024-07-18 11:15 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +      return
В цикл нужно заворачивать только подключение.  Заведи переменную (например, connected) со значением по умолчанию False. В конце блока try (а лучше - в блоке else) присваиваешь ей значение True, в except - False. И крутишь try-except пока она не True. Всё остальное делаешь после выхода из цикла

2024-07-18 11:19 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +sample_range_name_of_council_of_dormitories = "Совет общежитий (СО)!A2:B50"
см. самый последний коммент. Это всё не нужно хранить. Это должно передаваться параметром при вызове. "!A2:B50" у тебя везде повторяется. Это можно вынести. Например, добавлять в строку в начале выполнения функции `reading_google_sheets`

2024-07-18 11:20 UTC, NikitaShlapak commented on utils/Google_sheets.py
> +sample_range_name_of_council_of_dormitories = "Совет общежитий (СО)!A2:B50"
Если ты боишься забыть, что туда можно писать, а что - нет, вынеси это в документацию

2024-07-20 12:14 UTC, NikitaChichikin commented
Исправлена функция while и исправлены принимаемые аргументы функции

2024-07-22 10:20 UTC, merged